name: Test Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup latest Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Test
      run: yarn test --ci
